import { IAPSRecipeDiagram } from './aps-recipe-diagram.component';

export const DATASOURCE: IAPSRecipeDiagram[] = [{
    id: 1,
    codePims: 'AS6DZ',
    productName: 'ДТЛ Евро С д.т.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 6,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 1,
},
{
    id: 7,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 8,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 68,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 688,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 6567,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 65673,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 622,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 64667,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 64357,
    codePims: 'SLO',
    productName: 'ВТ-3.',
    productDeviation: 282.773,
    deviationQuality: 0,
},
{
    id: 999,
    codePims: 'SLO',
    productName: 'last-row',
    productDeviation: 282.773,
    deviationQuality: 0,
}];