---
before_script:
- echo $CI_JOB_STAGE
- date
- ls
- pwd

after_script:
- date

variables:
    GIT_SSL_NO_VERIFY: "1"
    DEPLOY_DOMAIN: deploy.funcoff.club

stages:
    - prebuild
    - test
    - build
    - deploy-review
    - staging
    - deploy
    - clean-on-failure


.init_template: &init
    tags:
        - evj-front


docker build:
    <<: *init
    stage: prebuild
    script:
        - echo "Prebuild checking... Getting docker container rdy."
        - docker container stop ${CI_PROJECT_NAME} || sleep 0.1
        - env
        - docker build -t ${CI_PROJECT_NAME} .
    only:
        - master
        - develop
        - merge_requests

testing website:
    <<: *init
    stage: test
    script:
        - echo "Doing some tests... Someone should add unit tests or whatever here"
        - docker run --rm --name ${CI_PROJECT_NAME} -p 8000:4200 -d ${CI_PROJECT_NAME}
        - ./init-docker.sh
    only:
        - merge_requests
 
build artifact:
    <<: *init
    stage: build
    script:
        - docker exec ${CI_PROJECT_NAME} ng build --prod || docker run --rm --name ${CI_PROJECT_NAME} -p 8000:4200 -d ${CI_PROJECT_NAME} ; docker exec ${CI_PROJECT_NAME} ng build --prod
        - docker cp ${CI_PROJECT_NAME}:/app/dist/evj ./public
        - docker container stop ${CI_PROJECT_NAME}
    only:
        - master
        - develop
          #- merge_requests
    artifacts:
        paths:
            - ./public

deploy review:
    <<: *init
    stage: deploy-review
    only:
        - merge_requests
    environment:
        name: review/${CI_COMMIT_REF_NAME}
        url: http://build.funcoff.club:8000
        on_stop: stop-review
    script:
        - sed -i -E "s/(<title>Evj)(<\/title>)/\1  |  ${CI_COMMIT_SHORT_SHA}\2/g" ./src/index.html

stop-review:
    <<: *init
    variables:
        GIT_STRATEGY: none
    stage: deploy-review
    only:
        - merge_requests
    script:
        - docker container stop ${CI_PROJECT_NAME}
    when: manual
    environment:
        name: review/${CI_COMMIT_REF_NAME}
        action: stop

staging:
    <<: *init
    stage: staging
    environment:
        name: staging
        url: http://${DEPLOY_DOMAIN}:88
    variables:
        CMD_REPLACE: sed -i -E "s/(<title>Evj)(<\/title>)/\1 | ${CI_COMMIT_SHORT_SHA} \2/g" /var/www/angular-staging.local/public/index.html
    script:
        - ssh root@${DEPLOY_DOMAIN} rm -rf /var/www/angular-staging.local/public
        - scp -r ./public root@${DEPLOY_DOMAIN}:/var/www/angular-staging.local
        - ssh root@${DEPLOY_DOMAIN} $CMD_REPLACE
        - ssh root@${DEPLOY_DOMAIN} "sed -i  's/:5555/:6555/g' /var/www/angular-staging.local/public/assets/config.json || sleep 0.1"
        - ssh root@${DEPLOY_DOMAIN} nginx -s reload
    only:
        - develop

prod:
    <<: *init
    stage: deploy
    environment:
        name: prod
        url: http://${DEPLOY_DOMAIN}:80
    variables:
        CMD_REPLACE: sed -i -E "s/(<title>Evj)(<\/title>)/\1 | ${CI_COMMIT_SHORT_SHA} \2/g" /var/www/angular.local/public/index.html
    script:
        - ssh root@${DEPLOY_DOMAIN} rm -rf /var/www/angular.local/public
        - scp -r ./public root@${DEPLOY_DOMAIN}:/var/www/angular.local
        - ssh root@${DEPLOY_DOMAIN} $CMD_REPLACE
        - ssh root@${DEPLOY_DOMAIN} "sed -i  's/:6555/:5555/g' /var/www/angular.local/public/assets/config.json || sleep 0.1"
        - ssh root@${DEPLOY_DOMAIN} nginx -s reload
    only:
        - master

clean on failure:
    <<: *init
    stage: clean-on-failure
    script:
        - docker container stop ${CI_PROJECT_NAME}
    when: on_failure
