---
include:
  - project: 'oaovd/osspu/evj/infra/pipelines'
    file: '/pipelines/angular-docker-helm-main.yml'

variables:
  # legacy
  ENV_STAGES_FILE: "evj-front.env"
  S3_RELEASE_BUCKET: "gazgolder/release-tags/${CI_PROJECT_NAME}"
  
  # global lvl
  GIT_DEPTH: 3
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1 
  DOCKER_DRIVER: overlay2
  GIT_SSL_NO_VERIFY: "1"
  PROJECT_NAME: "front"
  CACHE_KEY: "$CI_PROJECT_NAME-$CI_PROJECT_ID-cache"

  # CI STAGES LVL
  ## angular pipelines
  SEMVER_EXPORT_ON: "true"
  COMPILE_TARGET: "angular"
  IS_ALERTING: "true"
  
  # EXPORTING-SEMVER LVL
  ## skip build and don't upload to ftp (controlled from RELEASE prjct)
  SKIP_BUILD: $SKIP_BUILD
  NO_FTP: $NO_FTP

  ## semver controlling variables
  SR_MANUAL_TAG_RELEASE: "false"
  SR_IS_COMPILE: "true"
  SR_COMPILE_TARGET: "angular"
  SR_IS_MAKE_DOCKER_IMG: "true"
  SR_IS_EXPORTING: "true"
  SR_IS_ALERTING: "true"
  SR_SEMVER_RELEASE_DRY_RUN: "false"
  EXTERNAL_REGISTRY: "onpz.local/evj"

  # DOCKER BUILD LVL
  DOCKERHUB_URL: "registry.funcoff.club"
  DOCKER_REPO: "evj"
  DOCKERFILE_PACK: "./docker/Dockerfile.packing"
  DOCKER_EXPORT_PULL_TAG: "latest"

  # service lvl
  SERVICE_NAME: "front"
  EXTERNAL_DOCKER_IMG: "onpz.local/evj/front"
  
  # deploy lvl
  RELEASE: "front"
  IMG_VERSION: "latest" 
  NS: "evj"
  CHART: "./ci/front-chart"
  DOMAIN: "funcoff.club"
  INGRESS_PREFIX: "evj"

  # ALERTING
  ROCKETCHAT_PUBLISH_SUCCESS: "*${SERVICE_NAME}* / *New build coming*. Uploaded to gpn-ftp ->"
  ROCKETCHAT_PUBLISH_FAIL: "*BUILD ${SERVICE_NAME} FAILED*. See details below ->"
  ROCKETCHAT_RELEASE_SUCCESS: "*New release ${SERVICE_NAME} coming*. Uploaded to gpn-ftp ->"
  ROCKETCHAT_RELEASE_FAIL: "*RELEASE ${SERVICE_NAME} FAILED*. See details below ->"
  # AUTH_TOKEN_PUBLISH: $ROCKETCHAT_PIPELINES
  # AUTH_TOKEN_RELEASE: $ROCKETCHAT_RELEASE_TAGS

stages:
  - build
  - packing
  - deploy
  - alerting
  - release

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "devops"
    
.default_rules_refs_anchor: &default_rules_refs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "devops"


deliver-to-deploy:
  extends: .alpine-ssh-base
  stage: deploy
  variables:
    DEPLOY_DOMAIN: 192.168.0.23
    GIT_STRATEGY: none
    DEPLOY_PATH: "/var/www/angular-staging.local/public"
    CMD_REPLACE: sed -i -E "s/(<title>Evj)(<\/title>)/\1 | ${CI_COMMIT_SHORT_SHA} \2/g" /var/www/angular.local/public/index.html
  needs:
    - job: ng-build
      artifacts: true
  before_script:
    - cat /etc/hosts
  script:
    - ssh root@${DEPLOY_DOMAIN} rm -rf $DEPLOY_PATH
    - mv ./dist/evj public
    - scp -r ./public root@${DEPLOY_DOMAIN}:${DEPLOY_PATH//\/public}
    - ssh root@${DEPLOY_DOMAIN} $CMD_REPLACE
    - ssh root@${DEPLOY_DOMAIN} nginx -s reload
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "devops"

export-to-zyfra:
  stage: release
  variables:
    GIT_STRATEGY: none
  needs: []
  trigger:
    include: ci/export-images-child.yml
  <<: *default_rules_refs

export-to-zyfra-semantic:
  stage: release
  needs: []
  trigger:
    include:
      - project: 'oaovd/osspu/evj/infra/pipelines'
        file: '/pipelines/semantic-release-to-zyfra-tst.yml'
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $RELEASE == "ZYFRA_FRONT"
    # - if: $CI_COMMIT_BRANCH == "master"
    #   when: manual
    # - if: $CI_COMMIT_BRANCH == "devops"
    #   when: manual
    # - if: $CI_COMMIT_BRANCH == "alpha"
    #   when: manual

release-notes-maker:
  extends: .release-notes-tpl
  stage: release
  needs: []
  dependencies: []
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual

export-to-ftp:
  stage: release
  needs: []
  variables:
    SKIP_BUILD: $SKIP_BUILD
    # DOCKERHUB_URL: "nexus.funcoff.club"
    # DOCKER_REPO: "asplatform"
  trigger:
    include:
      - project: 'oaovd/osspu/evj/infra/pipelines'
        file: '/pipelines/semantic-release.yml'
  rules:
    - if: $SEMVER_EXPORT_ON == "false"
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $RUN_FROM == "release"
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual
    - if: $CI_COMMIT_BRANCH == "devops"
      when: manual
    - if: $CI_COMMIT_BRANCH == "alpha"
      when: manual

export-to-ftp-no-build:
  stage: release
  needs: []
  variables:
    SKIP_BUILD: "true"
    # DOCKERHUB_URL: "nexus.funcoff.club"
    # DOCKER_REPO: "asplatform"
  trigger:
    include:
      - project: 'oaovd/osspu/evj/infra/pipelines'
        file: '/pipelines/semantic-release.yml'
  rules:
    - if: $SEMVER_EXPORT_ON == "false"
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual
    - if: $CI_COMMIT_BRANCH == "devops"
      when: manual
    - if: $CI_COMMIT_BRANCH == "alpha"
      when: manual

semantic-release:
  stage: release
  needs: []
  variables:
    SKIP_BUILD: "true"
    SR_IS_EXPORTING: "false"
    # DOCKERHUB_URL: "nexus.funcoff.club"
    # DOCKER_REPO: "asplatform"
  trigger:
    include:
      - project: 'oaovd/osspu/evj/infra/pipelines'
        file: '/pipelines/semantic-release.yml'
  rules:
    - if: $SEMVER_EXPORT_ON == "false"
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual
    - if: $CI_COMMIT_BRANCH == "devops"
      when: manual
    - if: $CI_COMMIT_BRANCH == "alpha"
      when: manual
