plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
      # - dist/**/*.{js,css}
      - CHANGELOG.md
      - docs
      - package.json
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - "@semantic-release/gitlab":
    - "gitlabUrl": "https://gitlab.funcoff.club"
branches:
  - "master"
  - "develop"
  - "devops"
  - name: "alpha"
    prerelease: true
