plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - "@semantic-release/gitlab":
    - "gitlabUrl": "https://gitlab.funcoff.club"
branches:
  - "master"
  - "develop"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "devops"
    prerelease: true
