# base image
FROM gitlab.funcoff.club:4567/oaovd/osspu/evj/front/caches:17.03.2020
#FROM gitlab.funcoff.club:4567/oaovd/osspu/evj/front/caches:13.04.2020

# set working directory
#WORKDIR /app

# add '/app/node_moudles/.bin' to $PATH
#ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ./package.json /app/package.json
RUN npm install
#ENV NG_CLI_ANALYTICS=ci

# add app
COPY ./ /app

# start app
#CMD ng serve --host 0.0.0.0 --disableHostCheck

CMD sleep 80000 
