import { Component, OnInit } from '@angular/core';
import { IClaim } from '../../../../models/admin-panel';
import { IWidgets } from '../../../../models/widget.model';

@Component({
    selector: 'evj-admin-claims',
    templateUrl: './admin-claims.component.html',
    styleUrls: ['./admin-claims.component.scss'],
})
export class AdminClaimsComponent implements OnInit {
    public claims: IClaim[] = [
        {
            name: 'Открытые',
            id: 1,
        },
        {
            name: 'Открытые и доступные',
            id: 2,
        },
        {
            name: 'Открытые и доступные',
            id: 3,
        },
    ];

    public availableWidgets: IWidgets[] = [
        {
            code: null,
            id: '1',
            name: 'Экран диспетчера',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '2',
            name: 'Панель администратора',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '3',
            name: 'Передача смен',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '1',
            name: 'Экран диспетчера',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '2',
            name: 'Панель администратора',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '3',
            name: 'Передача смен',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '1',
            name: 'Экран диспетчера',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '2',
            name: 'Панель администратора',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '3',
            name: 'Передача смен',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '1',
            name: 'Экран диспетчера',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '2',
            name: 'Панель администратора',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '3',
            name: 'Передача смен',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '1',
            name: 'Экран диспетчера',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '2',
            name: 'Панель администратора',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '3',
            name: 'Передача смен',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '1',
            name: 'Экран диспетчера',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '2',
            name: 'Панель администратора',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '3',
            name: 'Передача смен',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '1',
            name: 'Экран диспетчера',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '2',
            name: 'Панель администратора',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '3',
            name: 'Передача смен',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '1',
            name: 'Экран диспетчера',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '2',
            name: 'Панель администратора',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '3',
            name: 'Передача смен',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '1',
            name: 'Экран диспетчера',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '2',
            name: 'Панель администратора',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
        {
            code: null,
            id: '3',
            name: 'Передача смен',
            title: null,
            units: null,
            widgetOptions: null,
            widgetType: null,
            categories: null,
        },
    ];

    constructor() {}

    ngOnInit(): void {}
}
