# ready to prod image
FROM nginx:1.19.1-alpine AS webserver
EXPOSE 80
COPY ./dist/evj /usr/share/nginx/html
COPY ./ci/entryPoint.sh /
ENV BASE_HREF "/"
ENV TITLE "AS-Evj"
ENTRYPOINT ["sh","/entryPoint.sh"]
CMD ["nginx", "-g", "daemon off;"]

