export const DATASOURCE = {
    sumInByDay: 0,
    sumInByHour: 0,
    section: [
        {
            name: 'Р-93',
            countFlowExceedingConfInterval: 0,
            flowOut: [
                {
                    code: 39,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FS98-93JD',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '28;53',
                },
                {
                    code: 40,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FS98-93GPN',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '29;54',
                },
                {
                    code: 41,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FS98-93АТ',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '30;55',
                },
                {
                    code: 42,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'Fr93per',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '31;50',
                },
            ],
            flowIn: [
                {
                    code: 17,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR-93',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '1;9',
                },
                {
                    code: 18,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR-93.r',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '2;10',
                },
            ],
            order: 0,
            objects: [
                {
                    code: 25,
                    id: '00000000-0000-0000-0000-000000000000',
                    name: 'P-93',
                    isEnable: false,
                    type: 'internal',
                    value: 583.821,
                },
                {
                    code: 28,
                    id: '2b80bd30-4511-11eb-aab0-9b6772837b11',
                    name: 'FS98-93JD',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '39;53',
                },
                {
                    code: 1,
                    id: '30ea9230-450e-11eb-aab0-9b6772837b11',
                    name: 'Приготовление из л. 413',
                    isEnable: false,
                    type: 'in',
                    related: '9;17',
                },
                {
                    code: 29,
                    id: '379f4f00-4511-11eb-aab0-9b6772837b11',
                    name: 'FS98-93GPN',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '40;54',
                },
                {
                    code: 30,
                    id: '46889990-4511-11eb-aab0-9b6772837b11',
                    name: 'FS98-93АТ',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '41;55',
                },
                {
                    code: 31,
                    id: '4f0b18e0-4511-11eb-aab0-9b6772837b11',
                    name: 'Fr93per',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '42;50',
                },
                {
                    code: 50,
                    id: '6d18bb30-4511-11eb-aab0-9b6772837b11',
                    name: 'PL98 АССБ',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '31;42;51;56',
                },
                {
                    code: 2,
                    id: '725b0b00-450e-11eb-aab0-9b6772837b11',
                    name: 'Перекачка',
                    isEnable: false,
                    type: 'in',
                    related: '10;18',
                },
                {
                    code: 51,
                    id: '782a22c0-4511-11eb-aab0-9b6772837b11',
                    name: 'Sys98',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '50;56',
                },
                {
                    code: 53,
                    id: '831e3e50-4511-11eb-aab0-9b6772837b11',
                    name: 'На отгрузку (ж/д цс)',
                    isEnable: false,
                    type: 'out',
                    related: '28;39',
                },
                {
                    code: 54,
                    id: '8bb8b270-4511-11eb-aab0-9b6772837b11',
                    name: 'Газпром-нефть - Омск',
                    isEnable: false,
                    type: 'out',
                    related: '29;40',
                },
                {
                    code: 55,
                    id: '97227330-4511-11eb-aab0-9b6772837b11',
                    name: 'На отгрузку (а/т)',
                    isEnable: false,
                    type: 'out',
                    related: '30;41',
                },
                {
                    code: 56,
                    id: '9f164710-4511-11eb-aab0-9b6772837b11',
                    name: 'В коллектор АССБ',
                    isEnable: false,
                    type: 'out',
                    related: '50;51',
                },
                {
                    code: 9,
                    id: 'b2de64b0-450e-11eb-aab0-9b6772837b11',
                    name: 'FR-93',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '1;17',
                },
                {
                    code: 10,
                    id: 'c450f230-450e-11eb-aab0-9b6772837b11',
                    name: 'FR-93.r',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '2;18',
                },
            ],
            deltaHour: 0,
            deltaHourByPercent: 0,
            delta: 0,
            deltaByPercent: 0,
            balanceAllowHour: 0,
            balanceAllowHourByPercent: 0,
            balanceAllow: 0,
            balanceAllowByPercent: 0,
            massIn: 0,
            massInDay: 0,
            massInDayDev: 0,
            massInHour: 0,
            massInHourDev: 0,
            massOut: 0,
            massOutDay: 0,
            massOutDayDev: 0,
            massOutHour: 0,
            massOutHourDev: 0,
            value: 583.821,
            code: '25',
        },
        {
            name: 'Р-94',
            countFlowExceedingConfInterval: 0,
            flowOut: [
                {
                    code: 43,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'Fr94per',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '32;50',
                },
                {
                    code: 44,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FS98-94JD',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '33;58',
                },
                {
                    code: 45,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FS98-94GPN',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '34;59',
                },
                {
                    code: 46,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FS98-94АТ',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '35;60',
                },
                {
                    code: 52,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FS98Dr',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '50;57',
                },
            ],
            flowIn: [
                {
                    code: 19,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR-94',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '3;11;66;74;82',
                },
                {
                    code: 20,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR-94.r',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '4;12',
                },
            ],
            order: 0,
            objects: [
                {
                    code: 35,
                    id: '00000000-0000-0000-0000-000000000000',
                    name: 'FS98-94АТ',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '46;60',
                },
                {
                    code: 57,
                    id: '474feef0-4516-11eb-aab0-9b6772837b11',
                    name: 'В коллектор дренажа',
                    isEnable: false,
                    type: 'out',
                    related: '50;52',
                },
                {
                    code: 58,
                    id: '554e1630-4516-11eb-aab0-9b6772837b11',
                    name: 'На отгрузку (ж/д цс)',
                    isEnable: false,
                    type: 'out',
                    related: '33;44',
                },
                {
                    code: 59,
                    id: '5f7803f0-4516-11eb-aab0-9b6772837b11',
                    name: 'Газпром-нефть - Омск',
                    isEnable: false,
                    type: 'out',
                    related: '34;45',
                },
                {
                    code: 3,
                    id: '611d08c0-4513-11eb-aab0-9b6772837b11',
                    name: 'Приготовление из л. 413',
                    isEnable: false,
                    type: 'in',
                    related: '11;19',
                },
                {
                    code: 60,
                    id: '6890a8c0-4516-11eb-aab0-9b6772837b11',
                    name: 'На отгрузку (а/т)',
                    isEnable: false,
                    type: 'out',
                    related: '35;46',
                },
                {
                    code: 4,
                    id: '705b0300-4513-11eb-aab0-9b6772837b11',
                    name: 'Перекачка',
                    isEnable: false,
                    type: 'in',
                    related: '12;20',
                },
                {
                    code: 11,
                    id: 'b15401e0-4513-11eb-aab0-9b6772837b11',
                    name: 'FR-94',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '3;19',
                },
                {
                    code: 12,
                    id: 'ba317270-4513-11eb-aab0-9b6772837b11',
                    name: 'FR-94.r',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '4;20',
                },
                {
                    code: 26,
                    id: '00000000-0000-0000-0000-000000000000',
                    name: 'P-94',
                    isEnable: false,
                    type: 'internal',
                    value: 1894.11,
                },
                {
                    code: 32,
                    id: 'd98d1890-4513-11eb-aab0-9b6772837b11',
                    name: 'Fr94per',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '43;50',
                },
                {
                    code: 33,
                    id: 'e2a7b930-4513-11eb-aab0-9b6772837b11',
                    name: 'FS98-94JD',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '44;58',
                },
                {
                    code: 34,
                    id: 'ed1fc6f0-4513-11eb-aab0-9b6772837b11',
                    name: 'FS98-94GPN',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '45;59',
                },
            ],
            deltaHour: 0,
            deltaHourByPercent: 0,
            delta: 0,
            deltaByPercent: 0,
            balanceAllowHour: 0,
            balanceAllowHourByPercent: 0,
            balanceAllow: 0,
            balanceAllowByPercent: 0,
            massIn: 0,
            massInDay: 0,
            massInDayDev: 0,
            massInHour: 0,
            massInHourDev: 0,
            massOut: 0,
            massOutDay: 0,
            massOutDayDev: 0,
            massOutHour: 0,
            massOutHourDev: 0,
            value: 1894.11,
            code: '26',
        },
        {
            name: 'Р-95',
            countFlowExceedingConfInterval: 0,
            flowOut: [
                {
                    code: 48,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR98OB95',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '37;62',
                },
                {
                    code: 49,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR80PER95',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '38;63',
                },
                {
                    code: 47,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR98JD95',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '36;61',
                },
            ],
            flowIn: [
                {
                    code: 21,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR-95_2',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '5;13',
                },
                {
                    code: 22,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR-95',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '6;14',
                },
                {
                    code: 23,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR-95pr',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '7;15',
                },
                {
                    code: 24,
                    productName: 'Алкилат',
                    valueMeasuring: 0,
                    valueEdit: 0,
                    valueCalculate: 0,
                    valueMoment: 0,
                    valueMomentPercent: 0,
                    valueByHour: 0,
                    valueByHourPercent: 0,
                    valueTank: 0,
                    valueTankPercent: 0,
                    tolerance: 0,
                    tag: 'FR-95.r',
                    isEnable: false,
                    isExceedingConfInterval: false,
                    accuracy: 0,
                    error: 0,
                    order: 0,
                    codeIn: '00000000-0000-0000-0000-000000000000',
                    codeOut: '00000000-0000-0000-0000-000000000000',
                    related: '8;16',
                },
            ],
            order: 0,
            objects: [
                {
                    code: 15,
                    id: '3b4855a0-4518-11eb-aab0-9b6772837b11',
                    name: 'FR-95pr',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '7;23',
                },
                {
                    code: 16,
                    id: '441c2940-4518-11eb-aab0-9b6772837b11',
                    name: 'FR-95.r',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '8;24',
                },
                {
                    code: 27,
                    id: '00000000-0000-0000-0000-000000000000',
                    name: 'P-95',
                    isEnable: false,
                    type: 'internal',
                    value: 613.756,
                },
                {
                    code: 36,
                    id: '56ea9d40-4518-11eb-aab0-9b6772837b11',
                    name: 'FR98JD95',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '47;61',
                },
                {
                    code: 37,
                    id: '5ec93b70-4518-11eb-aab0-9b6772837b11',
                    name: 'FR98OB95',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '48;62',
                },
                {
                    code: 38,
                    id: '670032d0-4518-11eb-aab0-9b6772837b11',
                    name: 'FR80PER95',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '49;63',
                },
                {
                    code: 5,
                    id: '73664a60-4517-11eb-aab0-9b6772837b11',
                    name: 'Приготовление из л. 413',
                    isEnable: false,
                    type: 'in',
                    related: '13;21',
                },
                {
                    code: 61,
                    id: '7cd493d0-4518-11eb-aab0-9b6772837b11',
                    name: 'На отгрузку (ж/д цс)',
                    isEnable: false,
                    type: 'out',
                    related: '36;47',
                },
                {
                    code: 62,
                    id: '85372f10-4518-11eb-aab0-9b6772837b11',
                    name: 'Газпром-нефть - Омск',
                    isEnable: false,
                    type: 'out',
                    related: '37;48',
                },
                {
                    code: 7,
                    id: '8d0e5330-4518-11eb-aab0-9b6772837b11',
                    name: 'Перекачка',
                    isEnable: false,
                    type: 'in',
                    related: '15;23',
                },
                {
                    code: 6,
                    id: 'a40cd1c0-4517-11eb-aab0-9b6772837b11',
                    name: 'Приготовление из л. 414',
                    isEnable: false,
                    type: 'in',
                    related: '14;22',
                },
                {
                    code: 63,
                    id: 'adbcfba0-4517-11eb-aab0-9b6772837b11',
                    name: 'Перекачка',
                    isEnable: false,
                    type: 'out',
                    related: '38;49',
                },
                {
                    code: 8,
                    id: 'bb0feec0-4517-11eb-aab0-9b6772837b11',
                    name: 'А95 с трубопровода',
                    isEnable: false,
                    type: 'in',
                    related: '16;24',
                },
                {
                    code: 13,
                    id: 'c3342170-4517-11eb-aab0-9b6772837b11',
                    name: 'FR-95_2',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '5;21',
                },
                {
                    code: 14,
                    id: 'cdee4140-4517-11eb-aab0-9b6772837b11',
                    name: 'FR-95',
                    isEnable: false,
                    type: 'buttonIn',
                    related: '6;22',
                },
            ],
            deltaHour: 0,
            deltaHourByPercent: 0,
            delta: 0,
            deltaByPercent: 0,
            balanceAllowHour: 0,
            balanceAllowHourByPercent: 0,
            balanceAllow: 0,
            balanceAllowByPercent: 0,
            massIn: 0,
            massInDay: 0,
            massInDayDev: 0,
            massInHour: 0,
            massInHourDev: 0,
            massOut: 0,
            massOutDay: 0,
            massOutDayDev: 0,
            massOutHour: 0,
            massOutHourDev: 0,
            value: 613.756,
            code: '27',
        },
    ],
    sumOutByDay: 0,
    sumOutByHour: 0,
    delta: 0,
    deltaByPersent: 0,
    deltaHour: 0,
    deltaHourByPercent: 0,
    lampOn: false,
    balanceAllow: 0,
    balanceAllowByPercent: 0,
    balanceAllowHour: 0,
    balanceAllowHourByPercent: 0,
    referenceBook: {
        manufacture: ['Производство \u21164', 'Товарное производство', 'Производство \u21161'],
        unit: [['Изомалк-2'], ['АССБ Авиасмеси', 'АССБ А-98', 'АССБ А-95'], ['АВТ-10']],
    },
    widgetType: 'sou-operational-accounting-system-new',
    isHistoricalDataSupported: true,
    subscriptionOptions: {
        manufacture: 'Товарное производство',
        name: 'АССБ А-98',
        timeStamp: 1611302665661,
    },
};
