export const DATASOURCE = [
    {
        id: 1,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: true,
        active: true,
    },
    {
        id: 2,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 3,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 29,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 10,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 15,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
];
