export const DATASOURCE = [
    {
        id: 1,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: true,
        active: true,
    },
    {
        id: 2,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 3,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 4,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 15,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 16,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 29,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 30,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 31,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 32,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 17,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 18,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 19,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 20,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
    {
        id: 34,
        text: 'FR-92',
        value: 10,
        percent: 20,
        deviation: false,
        active: true,
    },
];
