{{- $tier :=  .Values.microservice.labels.tier -}}
{{- $type :=  .Values.microservice.service.type -}}
{{- $port :=  .Values.microservice.service.port -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    tier: {{ $tier }}
spec:
  type: {{ $type }}
  selector:
    app: {{ include "fullname" . }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: {{ $port }}
---
